export const tags = [
    {name:'vegan',color:"#31FF85",checked:false},
    {name:'vegetarian',color:"#63FFA3",checked:false},
    {name:'baked goods',color:"#FFEC83",checked:false},
    {name:'meat',color:"#FF4343",checked:false},
    {name:'breakfast',color:"#81FFEE",checked:false},
    {name:'dinner',color:"#0B5B78",checked:false},
    {name:'curry',color:"#D8A10D",checked:false},
    {name:'lunch',color:"#FFCC42",checked:false},
    {name:'easy',color:"#FFDE86",checked:false},
    {name:'sandwich',color:"#DABF75",checked:false},
    {name:'gluten free',color:"#DFA300",checked:false},
    {name:'sauce',color:"#B83616",checked:false},
    {name:'salad',color:"#46E523",checked:false},
    {name:'soup',color:"#F3A620",checked:false},
    {name:'appetizer',color:"#FFFF93",checked:false},
    {name:'dessert',color:"#DDA312",checked:false},
    {name:'pasta',color:"#FF5A5A",checked:false},
    {name:'indian',color:"#B98B27",checked:false},
    {name:'italian',color:"#EF1818",checked:false},
    {name:'thai',color:"#B6E611",checked:false},
    {name:'greek',color:"#ECECEC",checked:false},
    {name:'chinese',color:"#FF7A7A",checked:false},
    {name:'smoothie',color:"#22BC0F",checked:false},
    {name:'brunch',color:"#BBFFB2",checked:false},
    
]