export default [
    {name:'vegan',color:"#31FF85"},
    {name:'vegetarian',color:"#63FFA3"},
    {name:'baked goods',color:"#FFEC83"},
    {name:'meat',color:"#FF4343"},
    {name:'breakfast',color:"#81FFEE"},
    {name:'dinner',color:"#0B5B78"},
    {name:'curry',color:"#D8A10D"},
    {name:'lunch',color:"#FFCC42"},
    {name:'easy',color:"#FFDE86"},
    {name:'sandwich',color:"#DABF75"},
    {name:'gluten free',color:"#DFA300"},
    {name:'sauce',color:"#B83616"},
    {name:'salad',color:"#46E523"},
    {name:'soup',color:"#F3A620"},
    {name:'appetizer',color:"#FFFF93"},
    {name:'dessert',color:"#DDA312"},
    {name:'pasta',color:"#FF5A5A"},
    {name:'indian',color:"#B98B27"},
    {name:'italian',color:"#EF1818"},
    {name:'thai',color:"#B6E611"},
    {name:'greek',color:"#ECECEC"},
    {name:'chinese',color:"#FF7A7A"},
    {name:'smoothie',color:"#22BC0F"},
    {name:'brunch',color:"#BBFFB2"},
    
]